{
  "openapi": "3.0.1",
  "info": {
    "title": "apiHelloWorld",
    "version": "v1"
  },
  "paths": {
    "/api/commands": {
      "get": {
        "tags": [
          "Commands"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommandReadDto"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommandReadDto"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommandReadDto"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Commands"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/CommandCreateDto"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CommandCreateDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CommandCreateDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CommandCreateDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/CommandCreateDto"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommandCreateDto"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommandCreateDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/commands/{id}": {
      "get": {
        "tags": [
          "Commands"
        ],
        "operationId": "GetCommandById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/CommandReadDto"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommandReadDto"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommandReadDto"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Commands"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/CommandUpdateDto"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CommandUpdateDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CommandUpdateDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CommandUpdateDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "patch": {
        "tags": [
          "Commands"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                },
                "nullable": true
              }
            },
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                },
                "nullable": true
              }
            },
            "text/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                },
                "nullable": true
              }
            },
            "application/*+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                },
                "nullable": true
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "delete": {
        "tags": [
          "Commands"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CommandReadDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "howTo": {
            "type": "string",
            "nullable": true
          },
          "line": {
            "type": "string",
            "nullable": true
          },
          "plataform": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CommandCreateDto": {
        "required": [
          "howTo",
          "line",
          "plataform"
        ],
        "type": "object",
        "properties": {
          "howTo": {
            "maxLength": 250,
            "type": "string"
          },
          "line": {
            "type": "string"
          },
          "plataform": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "CommandUpdateDto": {
        "required": [
          "howTo",
          "line",
          "plataform"
        ],
        "type": "object",
        "properties": {
          "howTo": {
            "maxLength": 250,
            "type": "string"
          },
          "line": {
            "type": "string"
          },
          "plataform": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "OperationType": {
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6
        ],
        "type": "integer",
        "format": "int32"
      },
      "Operation": {
        "type": "object",
        "properties": {
          "operationType": {
            "$ref": "#/components/schemas/OperationType"
          },
          "path": {
            "type": "string",
            "nullable": true
          },
          "op": {
            "type": "string",
            "nullable": true
          },
          "from": {
            "type": "string",
            "nullable": true
          },
          "value": {
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}